calibrations:
  poste:
    '100':
      intermediate_joint_angles:
      - -0.61
      - 75.93
      - -78.83
      - 0.79
      - 65.65
      - -9.31
      pregrasp_joint_angles:
      - 2.19
      - 92.81
      - -84.72
      - -4.57
      - 65.21
      - -6.59
      contact_joint_angles:
      - 2.46
      - 112.85
      - -84.9
      - -2.54
      - 52.91
      - -3.16
      table_height_mm: 100
      initial_pose_name: home
      carry_pose: home
      calibrated_at: '2026-09-08T06:18:07+00:00'
  rueda:
    '100':
      intermediate_coords:
      - 190.6
      - -4.5
      - 253.4
      - -48.94
      - 77.13
      - -50.09
      pregrasp_coords:
      - 209.4
      - -8.4
      - 91.9
      - -171.44
      - 13.18
      - -178.91
      contact_coords:
      - 217.8
      - -13.1
      - 49.7
      - -170.98
      - 12.61
      - -179.52
      intermediate_joint_angles:
      - -1.84
      - 11.07
      - -11.07
      - -9.4
      - -8.61
      - -0.26
      pregrasp_joint_angles:
      - 0.26
      - 64.24
      - -45.61
      - -9.84
      - 58.35
      - 4.39
      contact_joint_angles:
      - -0.87
      - 87.62
      - -67.41
      - -10.37
      - 57.3
      - 4.3
      execution_mode: joints
      table_height_mm: 100
      initial_pose_name: home
      carry_pose: home
      calibrated_at: '2026-09-09T10:19:13+00:00'
      frame_id: base_link
      gripper:
        open_value: 99
        close_value: 33
        speed_percent: 40.0
      operation: pick
