FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    sudo \
    git \
    curl \
    wget \
    nano \
    vim \
    less \
    procps \
    iproute2 \
    iputils-ping \
    net-tools \
    mesa-utils \
    python3-pip \
    python3-yaml \
    python3-rosdep \
    python3-vcstool \
    python3-colcon-common-extensions \
    ros-humble-gazebo-ros \
    ros-humble-gazebo-plugins \
    ros-humble-gazebo-ros2-control \
    ros-humble-ros2-control \
    ros-humble-ros2-controllers \
    ros-humble-controller-manager \
    ros-humble-mecanum-drive-controller \
    ros-humble-joint-state-broadcaster \
    ros-humble-joint-trajectory-controller \
    ros-humble-nav2-bringup \
    ros-humble-navigation2 \
    ros-humble-slam-toolbox \
    ros-humble-twist-mux \
    ros-humble-cv-bridge \
    ros-humble-image-transport \
    ros-humble-camera-info-manager \
    ros-humble-tf2-tools \
    ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*

# rosdep puede venir inicializado dependiendo de la imagen.
RUN if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then \
        rosdep init; \
    fi && \
    rosdep update

WORKDIR /workspace

# Evita algunos problemas Qt/OpenGL en contenedores.
ENV QT_X11_NO_MITSHM=1

CMD ["/bin/bash"]
